services:
  node-app:
    build: .
    container_name: farmashop-node-app
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    networks:
      - farmashop

networks:
  farmashop: